### ISSUE TITLE
COMPOST Issue 03 Launch Tasks

### ISSUE THREAD

**Issue by maisutton** [hyphacoop/compost.digital#7]
- [x] Schedule CMS onboarding session for Issue 03 contributors
- [x] Draft and finalize Issue 03 Foreword
- [x] Schedule virtual launch event
- [x] Submit session for DWeb Camp launch - Mai
- [x] Olu's cover image
- [x] Review issue + take note of final edits
- [x] Draft DP reflection piece with Mauve
- [x] Review/edit Back Cover
- [x] Review/edit About page
- [x] Support us pagew > $30K, where to put amount
- [x] Copyedit teasers
- [x] Add Erin's illos for section breaks
- [x] Finalize + upload DP reflection piece
- [x] Review/edit Support Us page
- [x] Final ordering of pieces
- [x] Create promo graphics for social media - Mai + Designer
- [ ] Create Issue 03 Playlist
- [x] Draft social media posts for launch - Mai

NEXT
- [ ] Schedule and plan LA launch event in July - Mai

**Comment by maisutton** [comment]
## Vincent's TODO:

- [x] DOLLY + NIALL's GAME: Not loading. D: 
- [x] PORTAL SEM PORTEIRAS: Edits requested by Marcela (in email)
- [x] GENERAL: Fix ordering of the pieces
- [x] LAKE'S PIECE (Relating to the infinite): Remove dropshadow
- [x] DOLLY + NIALL's GAME: We also need to add a "Please give it a minute to allow the game to load. Thank you for your patience."
- [x] MENU: ISSUE 03 needs to go to Home page
- [x] SUPPORT US Page: Amount in OC account is not displaying.
- [x] SUPPORT US Page: Add space and $ next to USD "Amount"
- [x] ERIN's PIECE: For summary/teaser, add "We seek to communicate the singularity of our experience, and it’s the limits and the peculiarities of a thing that give it character. The more unique, the more novel, a thing is, the more it will catch our eye."
- [x] FLUX PIECE: Edit teaser to: "Jakarta had drowned and for two decades she was claimed by the sea — until the government engaged some architects who designed Palm Jumeirah and Jebel Ali as a semi-Atlantis. We flew to Garut where the new airport was built on the reclaimed lands around Mount Papandayan, now near sea level, before taking a private boat to Jakarta."
- [x] SUPPORT US Page: Change order of buttons >> 1) Become a subscriber, 2) Contribute money, 3) Contribute ETH or tokens, 4) Supprt us on Gitcoin
- [x] MENU: Switch About Us and Support Us on the top of the Menu 
- [x] FOOTER: Link hover colors not working.
- [x] GENERAL: Can everything be shifted down in size entirely, by about 20%? It seems a bit zoomed in. This includes Issue 01 and Issue 02

## Mauve's TODO:
- [x] DOMAIN SWITCHOVER: To three.compost.digital >> Check all links 

## Ben's TODO:
- [x] BACK COVER: Hide authors who don't have a "personal project" listed

**Comment by fauno** [comment]
> MENU: Switch About Us and Support Us on the top of the Menu

You can filter by Menu items on the CMS and change the ordering

>  SUPPORT US Page: Change order of buttons >> 1) Become a subscriber, 2) Contribute money, 3) Contribute ETH or tokens, 4) Supprt us on Gitcoin

Idem

>  GENERAL: Can everything be shifted down in size entirely, by about 20%? It seems a bit zoomed in. This includes Issue 01 and Issue 02

You can change font sizes filtering by Theme and editing the article.  They're on rem units and usually 1rem = 16px.

**Comment by maisutton** [comment]
Issue 03 released! Great work everyone!!
